### PR TITLE
add customize template feature

### PR DESCRIPTION
**Pull request by cloverrose**
## Background
Sometimes I want to use mock with other format to follow existing code base.

## What
- add `templates` package

## How to use customize template
1. add a new file under `templates` package like `default.go`
2. build
3. run mokku with specifing template name in command line argument like `./mokku -t mytemplate`

### CODE REVIEW

**Comment by cloverrose** [comment]
Thank you for your review. I understood your requests.
Then I have a question, which is better to define `defaultTemplate` and `loadTemplateStringFromFile`, `/cmd/mokku/mokku.go` or `/template.go`?

1. If put them in `/cmd/mokku/mokku.go`, there is no exposed values but I need to duplicated define `defaultTemplate` in `/template_test.go` and `/cmd/mokku/mokku.go` become a little bit fat.
2. If put them in `/template.go` (or another file under `mokku` package), there are new exposed types.

**Comment by kinbiko** [comment]
Good point. Let's go with `1.`.
> [A little copying is better than a little dependency.](https://go-proverbs.github.io/)

Also, looks like you'll have to [enable GitHub actions on your fork](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories) in order to trigger the GitHub action workflow that contains testing/linting.

**Comment by yanolab** [comment]
Oh, I didn't know this PR... I created a new PR here https://github.com/kinbiko/mokku/pull/29
The difference between my idea and this is that my idea is using ENV value whereas this idea is using argument.

**Comment by kinbiko** [comment]
I think I prefer @yanolab's approach of using an environment variable to define the path instead of an argument. I think it's common for system paths to be stored in env vars, and this approach means that the command to run is the same (just `mokku`).

On the other hand, I appreciate the additional effort @cloverrose has done on this branch, and I think it would be quicker to modify this PR to use an environment variable than to review and address the other PR.

I'm going to merge this branch into a `next` branch, do some minor fixes, and then hopefully have this released by next week.

Thanks for both of your efforts, and for using `mokku`! 🙇

**Comment by cloverrose** [comment]
Oh, env approach is better.
My idea was started from another code generator, which needs to specify template files from some options.
But I want to use always the same mock.

**Pull request merged**
